---
- hosts: all
  become: yes
  vars:
   - php_memory_limit: "128M"
   - php_max_execution_time: "90"
   - php_upload_max_filesize: "256M"
   - php_enable_php_fpm: true
   - php_fpm_state: started
   - php_fpm_enabled_on_boot: true
   - php_enable_webserver: true

   - php_packages:
       - php
       - php-cli
       - php-common
       - php-mysql
       - php-apcu
       - php-fpm
       - php-mbstring
#       - php-devel
  roles:
    - { role: geerlingguy.php }
